sqlite features
valentinEutrope/Smith pull request #21
Opened 2022-01-12 13:02 UTC by cabbadie

- setup electron api in preload
- setup first query for getting worldList
- db file created with the worlds and tags tables

2022-01-16 19:45 UTC, valentinEutrope requested changes
Cool pour les nouveautés ! Juste essaye de faire le useEffect pour l'appel api ;)

2022-01-16 19:45 UTC, valentinEutrope commented on src/client/package.json
> +    "styled-bootstrap-grid": "^3.1.2",
styled-bootstrap-grid on va pouvoir le virer, ça sert à rien je crois x)

2022-01-16 19:45 UTC, valentinEutrope commented on src/client/src/components/WorldList/WorldList.js
> +  }
Tu n'a pas besoin de faire un if ici, la bonne pratique veut que tu appel ton API en suivant le lifecycle de ton composant, donc en utilisant un useEffect() qui est appelé automatiquement au moment où le composant est monté : https://fr.reactjs.org/docs/hooks-effect.html 

Tu as juste à lui passé worlds en dépendance : 

```js
useEffect(() => {   
   window.api.getWorldList().then(
      (result) => {
        setWorlds(result);
      },
      (err) => {
        toast.error(err.message, { id: "errGetWorldList" });
      }
    );
}, [worlds]);
```

Il faudra également créer un state de loading et d'erreur, mais je m'en occuperai si tu veux

2022-01-16 19:45 UTC, valentinEutrope commented on src/client/src/components/WorldList/WorldList.js
> +      <Toaster />
note pour plus tard : on l’appellera dans le App.js pour l'avoir directement sur toutes les pages

2022-01-16 19:45 UTC, valentinEutrope commented on src/client/src/components/WorldList/WorldList.js
> +                {world.tags ? <Tags tags={world.tags.split(",")} /> : null}
world.tags est une string ?

2022-01-17 14:26 UTC, cabbadie commented on src/client/src/components/WorldList/WorldList.js
> +  }
ah ok ! je connaissais pas bien le format de composants comme ça ^^ j'avais vu que les composants en mode objet avec des classes tout ça, je vais modifier ça

2022-01-17 14:27 UTC, cabbadie commented on src/client/src/components/WorldList/WorldList.js
> +      <Toaster />
Je peux le faire en modifiant la PR ;)

2022-01-17 14:28 UTC, cabbadie commented on src/client/src/components/WorldList/WorldList.js
> +                {world.tags ? <Tags tags={world.tags.split(",")} /> : null}
Je voyais l'utilisateur saisir des strings avec des ',' en fait, ou alors tu préfères passer par une liste où on ajoute des éléments? et enregistrer ça en json dans la DB?

2022-01-17 14:57 UTC, cabbadie commented on .gitignore
> +dist
Le "/" en premier marchait pas bien, à la limite il fallait "./", mais les nom tout court c'est ok

2022-01-17 14:59 UTC, cabbadie commented on .gitignore
> +**/*.sqbpro
J'utilise une outil, "DB Browser (SQLite)", qui me permet de gérer la db sqlite et me créé des fichiers projets de ce style

2022-01-17 15:00 UTC, cabbadie commented on src/client/electron-preload.js
> +        });
Le petit traitement mis au niveau de l'api pour avoir un tableau direct dans le front

2022-01-17 15:00 UTC, cabbadie commented on src/client/package.json
> -    "styled-bootstrap-grid": "^3.1.1",
Viré , re-testé sans lui, ça à l'air de rien impacter !

2022-01-17 15:01 UTC, cabbadie commented on src/client/src/App.js
> +      <Toaster />
Toaster mis au niveau App

2022-01-17 15:04 UTC, cabbadie reviewed
J'ai refait les choses un peu plus clean, hésite pas à me dire si tu vois quelque chose d'autre ! :p

2022-01-18 14:54 UTC, valentinEutrope commented on src/client/src/components/WorldList/WorldList.js
> +                {world.tags ? <Tags tags={world.tags.split(",")} /> : null}
Recevoir un tableau me semble être un format plus approprié, mais les 2 fonctionnent après

2022-01-18 14:55 UTC, valentinEutrope commented on src/client/src/App.js
> +      <Toaster />
nickel !

2022-01-18 15:00 UTC, valentinEutrope approved these changes
Nickel j'approuve ! Mais juste change la dépendance dans le useEffect() , je me suis planté dans mon commentaire ^^

2022-01-18 15:00 UTC, valentinEutrope commented on src/client/src/components/WorldList/WorldList.js
> +  }, [worlds]);
```suggestion
  }, [setWorlds]);
```

Je me suis planté dans mon commentaire :
il faut lui passer setWorlds en dépendance, tu n'utilise pas worlds dans le useEffect ^^

2022-01-18 15:00 UTC, valentinEutrope commented on src/client/src/components/WorldList/WorldList.js
> +    window.api.getWorldList().then(
Il me semble qu'il y a une raison mais on ne peut pas d'utiliser fetch() ici ?

2022-01-28 13:10 UTC, merged